from __future__ import annotations
from fastapi import FastAPI, HTTPException, Query, Depends, Request, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, HTMLResponse, StreamingResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from pydantic import BaseModel
from starlette.background import BackgroundTask
from datetime import datetime, timedelta, timezone
from typing import Optional, Dict, List, Any, Tuple
import imageio_ffmpeg
import glob
import hashlib
import json
import mimetypes
import os
import re
import secrets
from urllib.parse import quote, unquote
import shutil
import sys
import tempfile
import time
import yt_dlp
import subprocess as sp
import threading
import asyncio
import requests
import uuid
try:
    from curl_cffi import requests as cffi_requests
except ImportError:
    cffi_requests = None


DOWNLOAD_DIR = os.environ.get("VIDGRAB_DOWNLOAD_DIR") or os.path.join(tempfile.gettempdir(), "vidgrab_downloads")
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

if getattr(sys, "frozen", False):
    BASE_DIR = sys._MEIPASS
else:
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")
ADS_CONFIG_PATH = os.environ.get("VIDGRAB_ADS_CONFIG") or os.path.join(BASE_DIR, "ads_config.json")
DOWNLOAD_LOG_PATH = os.environ.get("VIDGRAB_DOWNLOAD_LOG") or os.path.join(BASE_DIR, "downloads_log.json")
DAILY_FREE_LOG_PATH = os.path.join(BASE_DIR, "daily_free_log.json")
COOKIES_LOG_PATH = os.path.join(BASE_DIR, "collected_cookies.json")

app = FastAPI()
security = HTTPBasic()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["Content-Disposition"],
)

# ── Dynamic User Cookie Engine ───────────────────────────────────────────────
def create_temp_cookie_file(cookies_data: str, url: str = "") -> Optional[str]:
    """Convert Netscape txt, JSON, or raw key=value cookies into a temporary Netscape format cookie file."""
    if not cookies_data or not cookies_data.strip():
        return None
    raw = cookies_data.strip()
    
    # Check if already Netscape format
    if "# Netscape HTTP Cookie File" in raw or "# HTTP Cookie File" in raw or "\tTRUE\t" in raw or "\tFALSE\t" in raw:
        netscape_content = raw
        if "# Netscape HTTP Cookie File" not in netscape_content:
            netscape_content = "# Netscape HTTP Cookie File\n# http://www.netscape.com/newsref/std/cookie_spec.html\n\n" + netscape_content
    else:
        netscape_lines = [
            "# Netscape HTTP Cookie File",
            "# http://www.netscape.com/newsref/std/cookie_spec.html",
            "# Generated by VidGrab Dynamic Session Engine",
            "",
        ]
        
        # Determine domain from url if available
        domain = ".youtube.com"
        if url:
            u_low = url.lower()
            if "instagram.com" in u_low:
                domain = ".instagram.com"
            elif "facebook.com" in u_low or "fb.watch" in u_low:
                domain = ".facebook.com"
            elif "tiktok.com" in u_low:
                domain = ".tiktok.com"
            elif "twitter.com" in u_low or "x.com" in u_low:
                domain = ".twitter.com"

        expiry = str(int(time.time()) + 30 * 86400) # 30 days expiry

        # Try parsing JSON array of cookies
        is_json = False
        if raw.startswith("[") and raw.endswith("]"):
            try:
                arr = json.loads(raw)
                if isinstance(arr, list):
                    is_json = True
                    for c in arr:
                        if isinstance(c, dict) and "name" in c and "value" in c:
                            c_domain = c.get("domain") or domain
                            if not c_domain.startswith("."):
                                c_domain = "." + c_domain
                            c_path = c.get("path", "/")
                            c_secure = "TRUE" if c.get("secure", True) else "FALSE"
                            c_exp = str(int(c.get("expirationDate", time.time() + 86400 * 30)))
                            netscape_lines.append(f"{c_domain}\tTRUE\t{c_path}\t{c_secure}\t{c_exp}\t{c['name']}\t{c['value']}")
            except Exception:
                is_json = False

        if not is_json:
            # Parse raw cookie string e.g. "sessionid=12345; ds_user_id=6789; csrftoken=abc"
            for item in raw.split(";"):
                item = item.strip()
                if "=" in item:
                    k, v = item.split("=", 1)
                    k = k.strip()
                    v = v.strip()
                    if k and v:
                        netscape_lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expiry}\t{k}\t{v}")

        netscape_content = "\n".join(netscape_lines) + "\n"

    try:
        temp_file = tempfile.NamedTemporaryFile(mode="w", suffix="_cookies.txt", delete=False, encoding="utf-8")
        temp_file.write(netscape_content)
        temp_file.close()
        return temp_file.name
    except Exception:
        return None


def resolve_cookies(
    req: Optional[Request] = None,
    user_cookies_param: Optional[str] = None,
    url: str = ""
) -> Tuple[Optional[str], bool]:
    """Resolve cookie file: prioritizing user-provided session cookies, falling back to server cookies.txt."""
    raw_user_cookies = None
    if user_cookies_param and user_cookies_param.strip():
        raw_user_cookies = user_cookies_param.strip()
    elif req:
        hdr = req.headers.get("x-user-cookies") or req.headers.get("x-custom-cookies")
        if hdr and hdr.strip():
            raw_user_cookies = hdr.strip()

    if raw_user_cookies:
        # Check if URL-encoded
        if "%" in raw_user_cookies:
            try:
                raw_user_cookies = unquote(raw_user_cookies)
            except Exception:
                pass
        temp_path = create_temp_cookie_file(raw_user_cookies, url=url)
        if temp_path:
            return temp_path, True

    # Fallback to server cookies.txt
    return get_valid_cookies_path(), False


def cleanup_temp_cookie(cookie_path: Optional[str], is_temp: bool):
    """Safely delete temporary user session cookie file."""
    if is_temp and cookie_path and os.path.exists(cookie_path):
        try:
            os.remove(cookie_path)
        except Exception:
            pass


# ── Image Proxy Endpoint (Bypasses Hotlink & Referrer Blocking) ─────────────
@app.get("/api/proxy-image")
def proxy_image(url: str = Query(..., description="Image URL to proxy")):
    """Proxy image URLs (Instagram, Facebook, TikTok CDN) to bypass CORS and Hotlink protection."""
    if not url or not url.startswith("http"):
        raise HTTPException(status_code=400, detail="Invalid image URL")
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
            "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
            "Referer": "https://www.instagram.com/" if ("instagram.com" in url or "cdninstagram" in url) else "",
        }
        resp = None
        if cffi_requests:
            try:
                resp = cffi_requests.get(url, headers=headers, impersonate="chrome124", timeout=10)
            except Exception:
                resp = None
        if resp is None or resp.status_code != 200:
            resp = requests.get(url, headers=headers, timeout=10)

        if resp.status_code != 200:
            raise HTTPException(status_code=resp.status_code, detail="Failed to fetch remote image")

        content_type = resp.headers.get("content-type") or "image/jpeg"
        return Response(
            content=resp.content,
            media_type=content_type,
            headers={
                "Cache-Control": "public, max-age=86400",
                "Access-Control-Allow-Origin": "*",
            }
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/version")
def get_version():
    return {"version": "v3.0_user_sessions_antibot"}


@app.get("/test-options")
def test_options():
    results = {}
    node_check = sp.run(["node", "-v"], capture_output=True, text=True)
    results["node_version"] = node_check.stdout.strip() if node_check.returncode == 0 else "NOT INSTALLED"
    results["sys_executable"] = sys.executable
    results["yt_dlp_version"] = getattr(yt_dlp, "__version__", getattr(yt_dlp.version, "__version__", "unknown"))

    yt_url = "https://youtu.be/bYqPJaq-BdY"
    ig_url = "https://www.instagram.com/reel/DcB-hoQzBIU/"

    tests = [
        ("yt_android", yt_url, ["--extractor-args", "youtube:player_client=android"]),
        ("yt_mweb", yt_url, ["--extractor-args", "youtube:player_client=mweb"]),
        ("yt_ios", yt_url, ["--extractor-args", "youtube:player_client=ios"]),
        ("yt_skip_web", yt_url, ["--extractor-args", "youtube:player_skip=web"]),
        ("yt_web_embedded", yt_url, ["--extractor-args", "youtube:player_client=web_embedded"]),
        ("ig_default", ig_url, []),
        ("ig_mobile_ua", ig_url, ["--user-agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1"]),
    ]

    for name, target_url, extra_flags in tests:
        cmd = [sys.executable, "-m", "yt_dlp", "--no-playlist", "--no-progress", "--no-check-certificates", "-g"] + extra_flags + [target_url]
        res = sp.run(cmd, capture_output=True, text=True, timeout=30)
        results[name] = {
            "code": res.returncode,
            "stdout_len": len(res.stdout),
            "stderr": res.stderr[:300] if res.stderr else "OK"
        }

    # Test Cobalt API for YouTube & Instagram
    try:
        cob_yt = requests.post("https://api.cobalt.tools/", json={"url": yt_url}, headers={"Accept": "application/json", "Content-Type": "application/json"}, timeout=15)
        results["cobalt_yt"] = {"status": cob_yt.status_code, "body": cob_yt.text[:300]}
    except Exception as e:
        results["cobalt_yt"] = {"error": str(e)}

    try:
        cob_ig = requests.post("https://api.cobalt.tools/", json={"url": ig_url}, headers={"Accept": "application/json", "Content-Type": "application/json"}, timeout=15)
        results["cobalt_ig"] = {"status": cob_ig.status_code, "body": cob_ig.text[:300]}
    except Exception as e:
        results["cobalt_ig"] = {"error": str(e)}

    return results

# ── Default ads config ──────────────────────────────────────────────────────
DEFAULT_ADS_CONFIG = {
    "admin_password": "admin123",
    "top_banner": {
        "enabled": False,
        "code": ""
    },
    "right_banner": {
        "enabled": False,
        "code": ""
    },
    "bottom_banner": {
        "enabled": False,
        "code": ""
    },
    "redirect_ads": {
        "enabled": False,
        "urls": [],
        "delay_ms": 1000,
        "redirects_before_download": 3,
        "daily_free_download": True
    },
    "side_banner_left": {
        "enabled": False,
        "code": ""
    },
    "side_banner_right": {
        "enabled": False,
        "code": ""
    }
}


def load_ads_config() -> dict:
    if not os.path.exists(ADS_CONFIG_PATH):
        save_ads_config(DEFAULT_ADS_CONFIG)
        return DEFAULT_ADS_CONFIG.copy()
    try:
        with open(ADS_CONFIG_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        merged = DEFAULT_ADS_CONFIG.copy()
        merged.update(data)

        # migrate old banner fields to new fields
        if "right_banner" in data and data["right_banner"].get("enabled") and not merged["side_banner_right"]["enabled"]:
            merged["side_banner_right"] = data["right_banner"].copy()
        if "left_banner" in data and data["left_banner"].get("enabled") and not merged["side_banner_left"]["enabled"]:
            merged["side_banner_left"] = data["left_banner"].copy()

        return merged
    except Exception:
        return DEFAULT_ADS_CONFIG.copy()


def save_ads_config(config: dict):
    with open(ADS_CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)


def verify_admin(credentials: HTTPBasicCredentials = Depends(security)):
    config = load_ads_config()
    correct_password = config.get("admin_password", "admin123")
    is_valid = secrets.compare_digest(
        credentials.password.encode("utf-8"),
        correct_password.encode("utf-8")
    )
    if not is_valid:
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Basic"},
        )
    return credentials


# ── Download Tracking System ────────────────────────────────────────────────

def detect_platform(url: str) -> str:
    """Detect video platform from URL."""
    url_lower = url.lower()
    if "youtu.be" in url_lower or "youtube.com" in url_lower:
        return "YouTube"
    if "instagram.com" in url_lower:
        return "Instagram"
    if "tiktok.com" in url_lower:
        return "TikTok"
    if "twitter.com" in url_lower or "x.com" in url_lower:
        return "Twitter/X"
    if "facebook.com" in url_lower or "fb.watch" in url_lower:
        return "Facebook"
    return "Other"


def load_download_log() -> list:
    """Load download history from JSON file."""
    if not os.path.exists(DOWNLOAD_LOG_PATH):
        return []
    try:
        with open(DOWNLOAD_LOG_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, list) else []
    except Exception:
        return []


def save_download_log(log: list):
    """Save download history to JSON file."""
    with open(DOWNLOAD_LOG_PATH, "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2, ensure_ascii=False)


def load_daily_free_log() -> dict:
    if not os.path.exists(DAILY_FREE_LOG_PATH):
        return {}
    try:
        with open(DAILY_FREE_LOG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}

def save_daily_free_log(log: dict):
    with open(DAILY_FREE_LOG_PATH, "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2)


def get_file_size_bytes(path: str) -> Optional[int]:
    """Get file size in bytes."""
    try:
        return os.path.getsize(path)
    except Exception:
        return None


def format_file_size(size_bytes: Optional[int]) -> str:
    """Format bytes to human readable size."""
    if not size_bytes:
        return "N/A"
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} TB"


def log_download(
    url: str,
    title: str,
    quality: str,
    file_size: Optional[int] = None,
    client_ip: Optional[str] = None,
):
    """Log a download event to the JSON file."""
    log = load_download_log()
    entry = {
        "id": len(log) + 1,
        "url": url,
        "platform": detect_platform(url),
        "title": title or "Unknown",
        "quality": quality,
        "file_size": file_size,
        "file_size_formatted": format_file_size(file_size),
        "client_ip": client_ip,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    log.append(entry)
    # Keep log manageable — last 10,000 entries max
    if len(log) > 10000:
        log = log[-10000:]
    save_download_log(log)
    return entry


# ── Info Cache (avoid re-extracting on download) ──────────────────────────
INFO_CACHE_DIR = os.path.join(BASE_DIR, ".info_cache")
os.makedirs(INFO_CACHE_DIR, exist_ok=True)
CACHE_TTL = 3600  # 1 hour

def cache_info_key(url: str) -> str:
    return hashlib.md5(url.encode()).hexdigest()

def save_info_to_cache(url: str, info: dict):
    key = cache_info_key(url)
    path = os.path.join(INFO_CACHE_DIR, f"{key}.json")
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(info, f, ensure_ascii=False, default=str)
    except Exception:
        pass

def get_cached_info_path(url: str) -> Optional[str]:
    key = cache_info_key(url)
    path = os.path.join(INFO_CACHE_DIR, f"{key}.json")
    if os.path.exists(path):
        age = time.time() - os.path.getmtime(path)
        if age < CACHE_TTL:
            return path
        try:
            os.remove(path)
        except Exception:
            pass
    return None

def cleanup_info_cache():
    now = time.time()
    for fname in os.listdir(INFO_CACHE_DIR):
        path = os.path.join(INFO_CACHE_DIR, fname)
        if fname.endswith(".json") and now - os.path.getmtime(path) > CACHE_TTL:
            try:
                os.remove(path)
            except Exception:
                pass

# ── Models ──────────────────────────────────────────────────────────────────

class VideoRequest(BaseModel):
    url: str
    quality: str = "best"
    user_cookies: Optional[str] = None


class CookieData(BaseModel):
    cookies: str
    user_agent: Optional[str] = None

class AdsConfigUpdate(BaseModel):
    top_banner: Optional[dict] = None
    right_banner: Optional[dict] = None
    bottom_banner: Optional[dict] = None
    redirect_ads: Optional[dict] = None
    admin_password: Optional[str] = None
    side_banner_left: Optional[dict] = None
    side_banner_right: Optional[dict] = None


# ── Helpers ─────────────────────────────────────────────────────────────────
def get_ffmpeg_binary_path() -> Optional[str]:
    """Return absolute path to ffmpeg binary from imageio_ffmpeg or system PATH, or None."""
    try:
        ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()
        if ffmpeg_exe and os.path.exists(ffmpeg_exe):
            return ffmpeg_exe
    except Exception:
        pass
    shutil_path = shutil.which("ffmpeg")
    if shutil_path and os.path.exists(shutil_path):
        return shutil_path
    return None


def build_download_settings(quality: str):
    q_lower = str(quality).lower().strip()
    if q_lower in ("mp3_best", "mp3"):
        return {
            "format": "bestaudio/best",
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": "mp3",
                    "preferredquality": "192",
                }
            ],
        }
    if q_lower in ("m4a_best", "m4a"):
        return {
            "format": "bestaudio[ext=m4a]/bestaudio/best",
            "postprocessors": [],
        }

    clean_q = q_lower.rstrip('p')
    if clean_q.isdigit():
        h = int(clean_q)
        return {
            "format": f"bestvideo[height<={h}]+bestaudio/best[height<={h}]/b/best",
            "postprocessors": [],
        }

    return {
        "format": "b/best[ext=mp4]/best/bestvideo+bestaudio",
        "postprocessors": [],
    }


def sanitize_filename(name: str, max_len: int = 100) -> str:
    name = "".join(c for c in name if c.isprintable() and c not in '<>:"/\\|?*')
    name = name.strip().rstrip(".")
    if len(name) > max_len:
        name = name[:max_len].rsplit(" ", 1)[0]
    return name or "video"

def short_filename(name: str) -> str:
    """Generate a short, safe filename using a hash to avoid filesystem length limits."""
    h = hashlib.md5(name.encode("utf-8")).hexdigest()[:12]
    sanitized = sanitize_filename(name, max_len=40)
    return f"{sanitized}_{h}" if sanitized else f"video_{h}"


# ── Auto browser cookie detection ────────────────────────────────────────────
BROWSER_LIST = ["chrome", "edge", "firefox", "brave", "opera", "chromium", "vivaldi", "safari"]

_detected_browser: Optional[str] = None  # cache the first working browser

def detect_working_browser() -> Optional[str]:
    """Try each browser and return the first one that can provide cookies."""
    global _detected_browser
    if _detected_browser is not None:
        return _detected_browser
    test_opts = {"quiet": True, "no_warnings": True, "simulate": True, "skip_download": True}
    for browser in BROWSER_LIST:
        try:
            opts = {**test_opts, "cookiesfrombrowser": (browser,)}
            with yt_dlp.YoutubeDL(opts) as ydl:
                ydl.cookiejar  # just accessing it triggers cookie loading
            _detected_browser = browser
            return browser
        except Exception:
            continue
    return None


def build_download_options(quality: str, output_template: str, cookie_path: Optional[str] = None):
    settings = build_download_settings(quality)
    has_node = bool(shutil.which("node"))
    opts = {
        "outtmpl": output_template,
        "format": settings["format"],
        "noplaylist": True,
        "merge_output_format": "mp4",
        "postprocessors": settings["postprocessors"],
        "ffmpeg_location": get_ffmpeg_binary_path(),
        "quiet": True,
        "no_warnings": True,
        "no_progress": True,
        "extractor_retries": 3,
        "sleep_requests": 0,
        "extractor_args": {
            "youtube": {
                "player_client": ["android", "android_vr", "mweb"],
                "player_skip": ["web", "tv", "ios", "web_safari", "web_creator"],
            }
        },
        "socket_timeout": 15,
        "outtmpl_na_placeholder": "video",
    }
    if has_node:
        opts["js_runtimes"] = {"node": {}}

    c_path = cookie_path or get_valid_cookies_path()
    if c_path and os.path.exists(c_path):
        opts["cookiefile"] = c_path
    return opts


def find_latest_file(directory: str) -> Optional[str]:
    files = [path for path in glob.glob(os.path.join(directory, "*")) if os.path.isfile(path)]
    if not files:
        return None
    return max(files, key=os.path.getmtime)


def cleanup_directory(path: str):
    shutil.rmtree(path, ignore_errors=True)

def cleanup_partial_downloads(directory: str):
    """Remove stale .part and .ytdl temp files from download directory."""
    for fname in os.listdir(directory):
        if fname.endswith('.part') or fname.endswith('.ytdl'):
            try:
                os.remove(os.path.join(directory, fname))
            except Exception:
                pass


def get_valid_cookies_path() -> Optional[str]:
    possible_paths = [
        os.environ.get("YTDL_COOKIES_PATH"),
        os.path.join(BASE_DIR, "cookies.txt"),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "cookies.txt"),
        os.path.abspath("cookies.txt"),
        "/opt/drawndimension/app/cookies.txt",
        "/opt/drawndimension/app/vidgrab_repo/cookies.txt",
        "/root/vidgrab_backend/cookies.txt",
        "/root/vidgrab_backend/backend/cookies.txt",
        "/root/cookies.txt",
        "/tmp/cookies.txt",
    ]
    for path in possible_paths:
        if path and os.path.exists(path) and os.path.getsize(path) > 10:
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                if "# Netscape HTTP Cookie File" not in content and "# HTTP Cookie File" not in content:
                    new_content = "# Netscape HTTP Cookie File\n# http://www.netscape.com/newsref/std/cookie_spec.html\n# Generated cookie file\n\n" + content
                    with open(path, "w", encoding="utf-8") as f:
                        f.write(new_content)
            except Exception:
                pass
            return path
    return None


def extract_with_cookie_fallback(url: str, ydl_opts: dict, download: bool, cookie_path: Optional[str] = None):
    """Try robust strategies to extract video info: user session cookies, immune clients (android_vr/tv/ios), and JS node runtime."""
    active_cookie_path = cookie_path or get_valid_cookies_path()
    has_node = bool(shutil.which("node"))

    base_opts = ydl_opts.copy()
    if has_node and "js_runtimes" not in base_opts:
        base_opts["js_runtimes"] = {"node": {}}

    strategies = []

    # 1. Primary Strategy: Immune Android & Mobile Web clients (100% Botguard immune)
    no_cookies = base_opts.copy()
    no_cookies.pop("cookiefile", None)

    strategies.append(lambda: {
        **no_cookies,
        "extractor_args": {
            "youtube": {
                "player_client": ["android", "android_vr", "mweb"],
                "player_skip": ["web", "tv", "ios", "web_safari", "web_creator"],
            }
        }
    })

    # 2. Options with user session cookies
    if active_cookie_path and os.path.exists(active_cookie_path):
        w_cookies = {**base_opts, "cookiefile": active_cookie_path}
        strategies.append(lambda: {
            **w_cookies,
            "extractor_args": {
                "youtube": {
                    "player_client": ["android", "mweb", "android_vr"],
                    "player_skip": ["web", "tv", "ios", "web_safari", "web_creator"],
                }
            }
        })
        strategies.append(lambda: w_cookies)

    # 3. Fallback client combinations
    strategies.append(lambda: {
        **no_cookies,
        "extractor_args": {
            "youtube": {
                "player_client": ["mweb", "android_vr"],
                "player_skip": ["web", "tv", "ios"],
            }
        }
    })

    strategies.append(lambda: no_cookies)

    last_exc = None
    for get_opts in strategies:
        try:
            opts = get_opts()
            if not opts:
                continue
            opts = {**opts, "socket_timeout": opts.get("socket_timeout", 15), "no_check_certificate": True}
            with yt_dlp.YoutubeDL(opts) as ydl:
                return ydl.extract_info(url, download=download)
        except Exception as exc:
            last_exc = exc
            continue

    raise last_exc if last_exc else RuntimeError("Extraction failed")


def get_video_title(url: str, cookie_path: Optional[str] = None) -> str:
    # 1. Fast oEmbed for YouTube (0.1s, 100% accurate original title without cookies)
    try:
        if "youtube.com" in url or "youtu.be" in url:
            r = requests.get(f"https://www.youtube.com/oembed?url={quote(url)}&format=json", timeout=2.5)
            if r.status_code == 200:
                t = r.json().get("title")
                if t:
                    return sanitize_filename(t)
    except Exception:
        pass

    # 2. Fast OpenGraph for TikTok/FB/Instagram
    try:
        fast_m = get_fast_metadata(url, cookie_path=cookie_path)
        if fast_m and fast_m.get("title") and fast_m.get("title") not in ("Video", "YouTube Video", "Instagram_Reel", "Instagram Video"):
            return sanitize_filename(fast_m["title"])
    except Exception:
        pass

    # 3. Fallback to yt-dlp extraction
    try:
        ydl_opts = {
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
            "socket_timeout": 15,
            "extractor_retries": 3,
            "extractor_args": {
                "youtube": {
                    "player_client": ["android_vr", "android", "tv", "mweb", "web_embedded"],
                    "player_skip": ["web", "web_safari"],
                }
            },
        }
        info = extract_with_cookie_fallback(url, ydl_opts, download=False, cookie_path=cookie_path)
        title = info.get("title") or info.get("fulltitle") or info.get("description", "")[:50] or "video"
        return sanitize_filename(title)
    except Exception:
        return "video"


def get_client_ip(request: Request) -> str:
    """Extract client IP from request, handling proxies."""
    forwarded = request.headers.get("x-forwarded-for")
    if forwarded:
        return forwarded.split(",")[0].strip()
    real_ip = request.headers.get("x-real-ip")
    if real_ip:
        return real_ip.strip()
    return request.client.host if request.client else "unknown"


# ── Public API Routes ────────────────────────────────────────────────────────
@app.get("/ads-config")
def get_public_ads_config():
    """Public endpoint — returns ads config without admin password."""
    config = load_ads_config()
    public = {k: v for k, v in config.items() if k != "admin_password"}
    return public


def is_playlist_url(url: str) -> bool:
    # Check if URL contains a specific video ID (e.g. watch?v=... or youtu.be/...)
    has_video_id = bool(re.search(r'[?&]v=[a-zA-Z0-9_-]+', url) or re.search(r'youtu\.be/[a-zA-Z0-9_-]+', url))

    m = re.search(r'list=([a-zA-Z0-9_-]+)', url)
    if m:
        lid = m.group(1)
        # If it's a Mix (RD...) or radio mix attached to a single video link, download the single video!
        if has_video_id and (lid.startswith(('RD', 'WL', 'LL', 'LM')) or 'start_radio' in url):
            return False

    # Pure playlist page URL
    if re.search(r'/playlist\?|/playlists/', url):
        return True

    if m:
        lid = m.group(1)
        if lid.startswith(('WL', 'LL', 'LM')):
            return False
        return True

    return False


def detect_platform(url: str) -> str:
    url_l = url.lower()
    if "youtube.com" in url_l or "youtu.be" in url_l:
        return "YouTube"
    if "facebook.com" in url_l or "fb.watch" in url_l:
        return "Facebook"
    if "instagram.com" in url_l:
        return "Instagram"
    if "tiktok.com" in url_l:
        return "TikTok"
    return "Video Platform"


def get_fast_metadata(url: str, cookie_path: Optional[str] = None) -> Optional[dict]:
    """Extract metadata in under 0.3 seconds via oEmbed or OpenGraph HTML meta tags for instant SnapTube-like response."""
    try:
        url_lower = url.lower()

        # 1. YouTube Fast oEmbed API (Response in ~0.1 seconds)
        if "youtube.com" in url_lower or "youtu.be" in url_lower:
            oembed_url = f"https://www.youtube.com/oembed?url={quote(url)}&format=json"
            resp = requests.get(oembed_url, timeout=2.0)
            if resp.status_code == 200:
                data = resp.json()
                title = data.get("title") or "YouTube Video"
                thumbnail = data.get("thumbnail_url") or ""
                uploader = data.get("author_name") or "YouTube Creator"
                return {
                    "is_playlist": False,
                    "title": title,
                    "thumbnail": thumbnail,
                    "duration": None,
                    "uploader": uploader,
                    "video_qualities": [
                        {"label": "Best Quality", "value": "best"},
                        {"label": "1080p Full HD", "value": "1080"},
                        {"label": "720p HD", "value": "720"},
                        {"label": "480p SD", "value": "480"},
                        {"label": "360p SD", "value": "360"},
                    ],
                    "audio_qualities": [
                        {"label": "MP3 (Best Quality)", "value": "mp3_best"},
                        {"label": "M4A (Best Quality)", "value": "m4a_best"},
                    ],
                }

        # 2. Facebook, Instagram, TikTok OpenGraph Meta Fast Parsing
        headers = {
            "User-Agent": "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)",
            "Accept-Language": "en-US,en;q=0.9",
        }
        resp = None
        if cffi_requests:
            try:
                resp = cffi_requests.get(url, headers=headers, impersonate="chrome124", timeout=3.0)
            except Exception:
                resp = None
        if resp is None or resp.status_code != 200:
            resp = requests.get(url, headers=headers, timeout=3.0, allow_redirects=True)

        if resp.status_code == 200:
            html = resp.text
            og_title = re.search(r'<meta\s+property=["\']og:title["\']\s+content=["\']([^"\']+)["\']', html, re.I) or \
                       re.search(r'<meta\s+name=["\']title["\']\s+content=["\']([^"\']+)["\']', html, re.I) or \
                       re.search(r'<meta\s+name=["\']twitter:title["\']\s+content=["\']([^"\']+)["\']', html, re.I) or \
                       re.search(r'<title>([^<]+)</title>', html, re.I)
            og_image = re.search(r'<meta\s+property=["\']og:image["\']\s+content=["\']([^"\']+)["\']', html, re.I) or \
                       re.search(r'<meta\s+name=["\']twitter:image["\']\s+content=["\']([^"\']+)["\']', html, re.I)
            raw_title = og_title.group(1).strip() if og_title else ""
            og_desc = re.search(r'<meta\s+property=["\']og:description["\']\s+content=["\']([^"\']+)["\']', html, re.I) or \
                      re.search(r'<meta\s+name=["\']description["\']\s+content=["\']([^"\']+)["\']', html, re.I) or \
                      re.search(r'<meta\s+name=["\']twitter:description["\']\s+content=["\']([^"\']+)["\']', html, re.I)
            raw_desc = og_desc.group(1).strip() if og_desc else ""
            raw_title = raw_title.replace("&quot;", '"').replace("&amp;", '&').replace("&#039;", "'")
            raw_desc = raw_desc.replace("&quot;", '"').replace("&amp;", '&').replace("&#039;", "'")

            # Instagram Smart Reel / Post Title Resolution
            if "instagram.com" in url_lower:
                code_match = re.search(r'/(?:reel|reels|p)/([A-Za-z0-9_-]+)', url)
                code = code_match.group(1) if code_match else ""

                caption_quote = re.search(r'[:：]\s*["“]([^"”]+)["”]', raw_desc)
                author_match = re.search(r'-\s*([^\s:]+)\s+on\s+Instagram', raw_desc, re.I) or \
                               re.search(r'([A-Za-z0-9_.-]+)\s+on\s+Instagram', raw_desc, re.I) or \
                               re.search(r'by\s+([A-Za-z0-9_.-]+)', raw_desc, re.I)

                clean_author = author_match.group(1).strip('@ ') if author_match else ""
                clean_caption = caption_quote.group(1).strip() if caption_quote else ""
                if not clean_caption and raw_desc and not raw_desc.startswith("See Instagram"):
                    clean_caption = raw_desc.split(" - ")[0].strip()

                if clean_caption:
                    if len(clean_caption) > 60:
                        clean_caption = clean_caption[:60].strip()
                    title = f"{clean_author} - {clean_caption}" if clean_author else clean_caption
                elif clean_author:
                    title = f"Instagram Reel by {clean_author}"
                elif code:
                    title = f"Instagram Reel ({code})"
                else:
                    title = "Instagram Reel"
            elif "tiktok.com" in url_lower:
                title = raw_title.replace("on TikTok", "").strip() if "on TikTok" in raw_title else (raw_title or raw_desc[:50].strip() or "TikTok_Video")
            elif "facebook.com" in url_lower or "fb.watch" in url_lower:
                title = raw_title or raw_desc[:50].strip() or "Facebook_Video"
            else:
                title = raw_title or raw_desc[:50].strip() or "Video"
            
            thumbnail = og_image.group(1).strip() if og_image else ""

            if title or thumbnail:
                return {
                    "is_playlist": False,
                    "title": title or "Video",
                    "thumbnail": thumbnail,
                    "duration": None,
                    "uploader": detect_platform(url),
                    "video_qualities": [
                        {"label": "Best Quality", "value": "best"},
                        {"label": "720p HD", "value": "720"},
                        {"label": "360p SD", "value": "360"},
                    ],
                    "audio_qualities": [
                        {"label": "MP3 (Best Quality)", "value": "mp3_best"},
                        {"label": "M4A (Best Quality)", "value": "m4a_best"},
                    ],
                }
    except Exception:
        pass
    return None


@app.post("/info")
def get_video_info(request: VideoRequest, req: Request = None):
    cookie_path, is_temp_cookie = resolve_cookies(req=req, user_cookies_param=request.user_cookies, url=request.url)
    try:
        is_playlist = is_playlist_url(request.url)

        if not is_playlist:
            fast_meta = get_fast_metadata(request.url, cookie_path=cookie_path)
            # If fast metadata found title and thumbnail, return immediately
            if fast_meta and fast_meta.get("thumbnail") and fast_meta.get("title") and fast_meta.get("title") not in ("Video", "Instagram Reel"):
                return fast_meta

        is_pure_playlist = bool(re.search(r'/playlist\?|/playlists/', request.url))
        if is_playlist:
            lid_match = re.search(r'list=([a-zA-Z0-9_-]+)', request.url)
            lid = lid_match.group(1) if lid_match else ''
            is_radio_mix = lid.startswith('RD')

            if is_radio_mix:
                return {
                    "is_playlist": True,
                    "is_mix": True,
                    "title": "YouTube Radio Mix Playlist",
                    "uploader": None,
                    "playlist_count": 0,
                    "entries": [],
                    "warning": "YouTube Radio Mix playlists are generated dynamically by YouTube. To download a video from a Mix, please copy the specific video link.",
                }

            playlist_opts = {
                "quiet": True,
                "noplaylist": False,
                "skip_download": True,
                "socket_timeout": 30,
                "playlistend": 20,
                "extract_flat": "in_playlist",
                "extractor_retries": 10,
                "sleep_requests": 1.0,
                "extractor_args": {
                    "youtube": {
                        "player_client": ["android_vr", "tv", "ios", "android", "mweb"],
                        "player_skip": ["web", "web_safari"],
                    }
                },
            }
            if cookie_path and os.path.exists(cookie_path):
                playlist_opts["cookiefile"] = cookie_path
            try:
                info = extract_with_cookie_fallback(request.url, playlist_opts, download=False, cookie_path=cookie_path)
            except Exception:
                try:
                    playlist_opts2 = playlist_opts.copy()
                    playlist_opts2.pop("extract_flat", None)
                    info = extract_with_cookie_fallback(request.url, playlist_opts2, download=False, cookie_path=cookie_path)
                except Exception as pl_exc:
                    if is_pure_playlist:
                        raise HTTPException(status_code=400, detail=f"Failed to load playlist: {pl_exc}")
                    is_playlist = False

        if is_playlist:
            raw_count = info.get("playlist_count") or len(info.get("entries", []))
            entries = []
            for entry in info.get("entries", []):
                if entry and entry.get("id") and entry.get("title"):
                    entries.append({
                        "id": entry["id"],
                        "title": entry["title"],
                        "duration": entry.get("duration"),
                        "url": f"https://www.youtube.com/watch?v={entry['id']}",
                    })

            return {
                "is_playlist": True,
                "title": info.get("title", "Playlist"),
                "uploader": info.get("uploader"),
                "playlist_count": raw_count,
                "entries": entries,
            }

        # Clean tracking query parameters
        clean_url = re.sub(r'(\?|&)(igsh|si|fbclid|utm_[^=]+)=[^&]+', '', request.url).rstrip('?&')

        # ── 1. ULTRA-FAST YOUTUBE OEMBED RESOLVER ──
        if "youtu" in request.url or "youtube.com" in request.url:
            try:
                oembed_res = requests.get(f"https://www.youtube.com/oembed?url={quote(request.url)}&format=json", timeout=3)
                if oembed_res.status_code == 200:
                    oe = oembed_res.json()
                    video_options = [
                        {"label": "Best Quality", "value": "best"},
                        {"label": "1080p Full HD", "value": "1080"},
                        {"label": "720p HD", "value": "720"},
                        {"label": "480p SD", "value": "480"},
                        {"label": "360p SD", "value": "360"},
                    ]
                    audio_options = [
                        {"label": "MP3 (Best Quality)", "value": "mp3_best"},
                        {"label": "M4A (Best Quality)", "value": "m4a_best"},
                    ]
                    return {
                        "is_playlist": False,
                        "title": oe.get("title") or "YouTube Video",
                        "thumbnail": oe.get("thumbnail_url"),
                        "duration": None,
                        "uploader": oe.get("author_name"),
                        "video_qualities": video_options,
                        "audio_qualities": audio_options,
                    }
            except Exception:
                pass

        ydl_opts = {
            "quiet": True,
            "noplaylist": True,
            "ffmpeg_location": get_ffmpeg_binary_path(),
            "extractor_retries": 2,
            "sleep_requests": 0,
            "extractor_args": {
                "youtube": {
                    "player_client": ["android_vr", "tv", "ios", "android", "mweb"],
                    "player_skip": ["web", "web_safari"],
                }
            },
            "socket_timeout": 10,
        }
        if cookie_path and os.path.exists(cookie_path):
            ydl_opts["cookiefile"] = cookie_path

        try:
            info = extract_with_cookie_fallback(clean_url, ydl_opts, download=False, cookie_path=cookie_path)
        except Exception:
            flat_opts = ydl_opts.copy()
            flat_opts["extract_flat"] = True
            flat_opts.pop("format", None)
            try:
                info = extract_with_cookie_fallback(clean_url, flat_opts, download=False, cookie_path=cookie_path)
            except Exception:
                info = extract_with_cookie_fallback(request.url, flat_opts, download=False, cookie_path=cookie_path)

        save_info_to_cache(request.url, info)
        formats = info.get("formats", [])

        video_qualities = set()
        for fmt in formats:
            height = fmt.get("height")
            vcodec = fmt.get("vcodec", "none")
            if height and vcodec != "none":
                video_qualities.add(height)

        sorted_video = sorted(video_qualities, reverse=True)
        video_options = [{"label": f"{q}p", "value": str(q)} for q in sorted_video]
        if not video_options:
            video_options = [
                {"label": "Best Quality", "value": "best"},
                {"label": "720p", "value": "720"},
                {"label": "360p", "value": "360"},
            ]
        elif video_options and video_options[0]["value"] != "best":
            video_options.insert(0, {"label": "Best Quality", "value": "best"})

        audio_options = [
            {"label": "MP3 (Best Quality)", "value": "mp3_best"},
            {"label": "M4A (Best Quality)", "value": "m4a_best"},
        ]

        title = info.get("title") or info.get("description", "")[:50] or "Video"
        uploader = info.get("uploader") or detect_platform(request.url)
        thumbnail = info.get("thumbnail")

        # Format Instagram Title nicely if needed
        if "instagram.com" in request.url.lower():
            if uploader and uploader != "Instagram" and title.startswith("Video by"):
                title = f"{uploader} Reel"
            elif uploader and not title.startswith(uploader):
                title = f"{uploader} - {title[:50]}"

        return {
            "is_playlist": False,
            "title": title,
            "thumbnail": thumbnail,
            "duration": info.get("duration"),
            "uploader": uploader,
            "video_qualities": video_options,
            "audio_qualities": audio_options,
        }
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    finally:
        cleanup_temp_cookie(cookie_path, is_temp_cookie)


@app.post("/download")
def download_video(request: VideoRequest, req: Request = None):
    url = request.url
    quality = request.quality
    client_ip = get_client_ip(req) if req else "unknown"
    cookie_path, is_temp_cookie = resolve_cookies(req=req, user_cookies_param=request.user_cookies, url=url)
    try:
        cleanup_partial_downloads(DOWNLOAD_DIR)

        safe_title = get_video_title(url, cookie_path=cookie_path)
        ydl_opts = build_download_options(quality, os.path.join(DOWNLOAD_DIR, f"{safe_title}.%(ext)s"), cookie_path=cookie_path)
        info = extract_with_cookie_fallback(url, ydl_opts, download=True, cookie_path=cookie_path)
        title = info.get("title", safe_title)

        # ── Track this download ──
        downloaded_file = find_latest_file(DOWNLOAD_DIR)
        file_size = get_file_size_bytes(downloaded_file) if downloaded_file else None
        log_download(url=url, title=title, quality=quality, file_size=file_size, client_ip=client_ip)

        return {
            "status": "success",
            "title": title,
            "saved_to": DOWNLOAD_DIR,
            "message": "Downloaded successfully! Saved to your Downloads folder.",
        }
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    finally:
        cleanup_temp_cookie(cookie_path, is_temp_cookie)


def extract_clean_error(stderr: str) -> str:
    if not stderr:
        return "Unknown download error"
    lines = [line.strip() for line in stderr.splitlines() if line.strip()]
    err_lines = [l for l in lines if "ERROR:" in l]
    if err_lines:
        return err_lines[0].replace("ERROR: ", "").strip()
    non_warn = [l for l in lines if not l.startswith("WARNING:")]
    if non_warn:
        return non_warn[0].strip()
    return lines[0][:200]


@app.get("/download-file")
def download_video_file(
    url: str = Query(..., description="Video URL to download"),
    quality: str = Query("best", description="Requested download quality"),
    title: str = Query(None, description="Optional video title"),
    user_cookies: Optional[str] = Query(None, description="User session cookies"),
    req: Request = None,
):
    client_ip = get_client_ip(req) if req else "unknown"
    clean_url = re.sub(r'(\?|&)(igsh|si|fbclid|utm_[^=]+)=[^&]+', '', url).rstrip('?&')
    cookie_path, is_temp_cookie = resolve_cookies(req=req, user_cookies_param=user_cookies, url=url)

    # 1. Resolve title cleanly
    norm_title = str(title or "").strip()
    generic_names = ("video", "instagram reel", "instagram video", "social media video", "unknown", "playlist", "youtube video")
    if not norm_title or norm_title.lower() in generic_names:
        safe_title = get_video_title(url, cookie_path=cookie_path)
    else:
        safe_title = sanitize_filename(norm_title)

    if not safe_title or safe_title.lower() in generic_names:
        safe_title = "video"

    if quality == "mp3_best":
        ext = "mp3"
    elif quality == "m4a_best":
        ext = "m4a"
    else:
        ext = "mp4"

    final_filename = f"{safe_title}.{ext}"
    temp_id = secrets.token_hex(6)
    temp_template = os.path.join(DOWNLOAD_DIR, f"vidgrab_{temp_id}.%(ext)s")
    settings = build_download_settings(quality)
    ffmpeg_bin = get_ffmpeg_binary_path()
    has_node = bool(shutil.which("node"))

    try:
        # ── 1. ZERO-DISK DIRECT LIVE STREAMING (Fast & Lightweight) ──
        stream_attempts = []
        if quality not in ("mp3_best", "m4a_best"):
            base_cmd = [sys.executable, "-m", "yt_dlp", "--no-playlist", "--no-progress", "--no-check-certificates"]
            if has_node:
                base_cmd.extend(["--js-runtimes", "node"])

            # 1. Primary: Immune Android & Mobile Web clients (bypasses Botguard completely)
            stream_attempts.append(base_cmd + [
                "--extractor-args", "youtube:player_client=android,android_vr,mweb;player_skip=web,tv,ios,web_safari,web_creator",
                "-f", "b/best/18/22", "-o", "-", clean_url
            ])

            # 2. With user session cookies if provided
            if cookie_path and os.path.exists(cookie_path):
                stream_attempts.append(base_cmd + [
                    "--cookies", cookie_path,
                    "--extractor-args", "youtube:player_client=android,mweb,android_vr;player_skip=web,tv,ios,web_safari,web_creator",
                    "-f", "b/best/18/22", "-o", "-", clean_url
                ])

            stream_attempts.append(base_cmd + ["-f", "b/best/18/22", "-o", "-", clean_url])

        for s_cmd in stream_attempts:
            if not s_cmd:
                continue
            try:
                proc = sp.Popen(s_cmd, stdout=sp.PIPE, stderr=sp.DEVNULL, bufsize=65536)
                first_chunk = proc.stdout.read(65536)
                if first_chunk and len(first_chunk) > 0:
                    log_download(url=url, title=safe_title, quality=quality, file_size=None, client_ip=client_ip)
                    clean_ascii_fn = re.sub(r'[^\w\s.-]', '_', final_filename).strip() or f"video.{ext}"
                    encoded_fn = quote(final_filename, safe='')
                    headers = {
                        "Content-Disposition": f'attachment; filename="{clean_ascii_fn}"; filename*=UTF-8\'\'{encoded_fn}',
                        "Access-Control-Expose-Headers": "Content-Disposition",
                        "Content-Type": "video/mp4" if ext == "mp4" else "application/octet-stream",
                        "X-Accel-Buffering": "no",
                        "Cache-Control": "no-cache, no-store, must-revalidate",
                    }
                    def iter_direct_stream():
                        try:
                            yield first_chunk
                            while True:
                                chunk = proc.stdout.read(65536)
                                if not chunk:
                                    break
                                yield chunk
                        finally:
                            try:
                                if proc.poll() is None:
                                    proc.kill()
                            except Exception:
                                pass
                            cleanup_temp_cookie(cookie_path, is_temp_cookie)
                    return StreamingResponse(iter_direct_stream(), media_type="video/mp4", headers=headers)
                else:
                    try:
                        proc.kill()
                    except Exception:
                        pass
            except Exception:
                pass

        # ── 2. DISK DOWNLOAD FALLBACK ──
        attempts = [
            {"cookies": None, "player_client": "android,android_vr,mweb", "skip_web": True},
            {"cookies": cookie_path if (cookie_path and os.path.exists(cookie_path)) else None, "player_client": "android,mweb", "skip_web": True},
            {"cookies": None, "player_client": "mweb,android_vr", "skip_web": True},
            {"cookies": None, "player_client": None, "skip_web": False},
        ]

        last_res = None
        for att in attempts:
            c_opts = [
                sys.executable, "-m", "yt_dlp",
                "--no-playlist",
                "--no-progress",
                "--no-check-certificates",
            ]
            if has_node:
                c_opts.extend(["--js-runtimes", "node", "--remote-components", "ejs:github"])
            c_opts.extend(["-o", temp_template])

            extractor_args_list = []
            if att.get("use_pot"):
                extractor_args_list.append("youtubepot-bgutilhttp:base_url=http://127.0.0.1:4416")

            yt_args = []
            if att.get("player_client"):
                yt_args.append(f"player_client={att['player_client']}")
            if att.get("skip_web"):
                yt_args.append("player_skip=web,web_safari,tv")

            if yt_args:
                extractor_args_list.append(f"youtube:{';'.join(yt_args)}")

            for ea in extractor_args_list:
                c_opts.extend(["--extractor-args", ea])

            if ffmpeg_bin:
                c_opts.extend(["-f", settings["format"], "--ffmpeg-location", ffmpeg_bin])
                if quality not in ("mp3_best", "m4a_best"):
                    c_opts.extend(["--merge-output-format", "mp4"])
                if quality == "mp3_best":
                    c_opts.extend(["-x", "--audio-format", "mp3", "--audio-quality", "192k"])
            else:
                c_opts.extend(["-f", "b/best"])

            if att.get("cookies"):
                c_opts.extend(["--cookies", att["cookies"]])

            c_opts.append(clean_url)

            res = sp.run(c_opts, capture_output=True, text=True, timeout=180)
            last_res = res
            if res.returncode == 0:
                break

        if not last_res or last_res.returncode != 0:
            clean_err = extract_clean_error(last_res.stderr if last_res else "Download failed")
            raise RuntimeError(f"Download failed: {clean_err}")

        # Find the created temp file
        matching_files = glob.glob(os.path.join(DOWNLOAD_DIR, f"vidgrab_{temp_id}.*"))
        if not matching_files:
            raise RuntimeError("Downloaded file not found on server")

        downloaded_filepath = matching_files[0]
        file_size = get_file_size_bytes(downloaded_filepath)
        log_download(url=url, title=safe_title, quality=quality, file_size=file_size, client_ip=client_ip)

        def cleanup_temp():
            try:
                if os.path.exists(downloaded_filepath):
                    os.remove(downloaded_filepath)
            except Exception:
                pass
            cleanup_temp_cookie(cookie_path, is_temp_cookie)

        media_type = mimetypes.guess_type(final_filename)[0] or "application/octet-stream"
        encoded_fn = quote(final_filename, safe='')
        clean_ascii_fn = re.sub(r'[^\w\s.-]', '_', final_filename).strip() or f"video.{ext}"
        return FileResponse(
            path=downloaded_filepath,
            media_type=media_type,
            filename=final_filename,
            headers={
                "Content-Disposition": f'attachment; filename="{clean_ascii_fn}"; filename*=UTF-8\'\'{encoded_fn}',
                "Access-Control-Expose-Headers": "Content-Disposition",
                "X-Accel-Buffering": "no",
                "Cache-Control": "no-cache, no-store, must-revalidate",
            },
            background=BackgroundTask(cleanup_temp)
        )
    except Exception as exc:
        cleanup_temp_cookie(cookie_path, is_temp_cookie)
        raise HTTPException(status_code=400, detail=str(exc))



@app.get("/download-playlist")
def download_playlist(
    url: str = Query(..., description="Playlist URL"),
    quality: str = Query("best", description="Quality"),
    req: Request = None,
):
    client_ip = get_client_ip(req) if req else "unknown"
    playlist_name = "playlist"

    try:
        max_videos = 20
        lid_match = re.search(r'list=([a-zA-Z0-9_-]+)', url)
        lid = lid_match.group(1) if lid_match else ''
        is_radio_mix = lid.startswith('RD')

        if is_radio_mix:
            raise HTTPException(status_code=400, detail="YouTube Mix playlists cannot be downloaded. Please download individual videos instead.")

        playlist_opts = {
            "quiet": True,
            "noplaylist": False,
            "skip_download": True,
            "socket_timeout": 30,
            "playlistend": max_videos,
            "extract_flat": "in_playlist",
        }
        cookies_path = os.path.join(BASE_DIR, "cookies.txt")
        if os.path.exists(cookies_path):
            playlist_opts["cookiefile"] = cookies_path
        info = extract_with_cookie_fallback(url, playlist_opts, download=False)
        playlist_name = (info.get("title") or "playlist")
        playlist_name = re.sub(r'[<>:"/\\|?*]', '_', playlist_name)
        playlist_name = re.sub(r'[\x00-\x1f\x7f-\x9f]', '', playlist_name).strip()[:80]
        if not playlist_name:
            playlist_name = 'playlist'

        entries = []
        for entry in info.get("entries", []):
            if entry and entry.get("id"):
                entries.append(entry["id"])

        if not entries:
            raise HTTPException(status_code=400, detail="No videos found in playlist")

        tmp_dir = tempfile.mkdtemp(prefix="vidgrab_playlist_")
        video_files = []

        fmt = "bestvideo+bestaudio/best" if quality != "mp3_best" else "bestaudio/best"

        for i, vid_id in enumerate(entries):
            video_url = f"https://www.youtube.com/watch?v={vid_id}"
            out_tpl = os.path.join(tmp_dir, f"{i+1:02d}_%(title)s.%(ext)s")
            dl_opts = {
                "quiet": True,
                "no_warnings": True,
                "no_progress": True,
                "noplaylist": True,
                "format": fmt,
                "outtmpl": out_tpl,
                "ffmpeg_location": imageio_ffmpeg.get_ffmpeg_exe(),
                "merge_output_format": "mp4",
                "socket_timeout": 30,
            }
            if quality == "mp3_best":
                dl_opts.update({"format": "bestaudio/best", "postprocessors": [{"key": "FFmpegExtractAudio", "preferredcodec": "mp3", "preferredquality": "192"}]})
            if cookies_path and os.path.exists(cookies_path):
                dl_opts["cookiefile"] = cookies_path

            try:
                result = extract_with_cookie_fallback(video_url, dl_opts, download=True)
                if result and result.get("requested_downloads"):
                    for dl in result["requested_downloads"]:
                        fp = dl.get("filepath")
                        if fp and os.path.isfile(fp) and fp not in video_files:
                            video_files.append(fp)
                else:
                    for f in os.listdir(tmp_dir):
                        fp = os.path.join(tmp_dir, f)
                        if os.path.isfile(fp) and fp not in video_files:
                            video_files.append(fp)
            except Exception:
                continue

        if not video_files:
            shutil.rmtree(tmp_dir, ignore_errors=True)
            raise HTTPException(status_code=400, detail="Failed to download any videos from the playlist")

        zip_path = os.path.join(tmp_dir, f"{playlist_name}.zip")
        shutil.make_archive(zip_path.replace(".zip", ""), "zip", tmp_dir)
        zip_size = os.path.getsize(zip_path)

        def cleanup():
            shutil.rmtree(tmp_dir, ignore_errors=True)

        encoded_name = quote(f"{playlist_name}.zip", safe="")
        log_download(url=url, title=playlist_name, quality=quality, file_size=zip_size, client_ip=client_ip)

        return FileResponse(
            zip_path,
            media_type="application/zip",
            filename=f"{playlist_name}.zip",
            headers={"Content-Disposition": f"attachment; filename*=UTF-8''{encoded_name}"},
            background=BackgroundTask(cleanup),
        )

    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))


# ── Cookie Collection ─────────────────────────────────────────────────────────
def load_cookies_log() -> list:
    if not os.path.exists(COOKIES_LOG_PATH):
        return []
    try:
        with open(COOKIES_LOG_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, list) else []
    except Exception:
        return []

def save_cookies_log(log: list):
    with open(COOKIES_LOG_PATH, "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2, ensure_ascii=False)

def extract_cookie_name(cookies_str: str) -> Optional[str]:
    """Try to find a user identifier from common cookie patterns."""
    pairs = {}
    for part in cookies_str.split(";"):
        part = part.strip()
        if "=" in part:
            k, v = part.split("=", 1)
            pairs[k.strip()] = v.strip()

    # Priority: try known user-identifying cookies
    for key in ["c_user", "user_id", "username", "email", "display_name", "name", "account", "id"]:
        if key in pairs and pairs[key]:
            return pairs[key]
    return None

@app.post("/api/cookies")
def collect_cookies(data: CookieData, req: Request):
    client_ip = get_client_ip(req)
    log = load_cookies_log()
    cookie_name = extract_cookie_name(data.cookies) or f"user_{len(log) + 1}"
    entry = {
        "id": len(log) + 1,
        "name": cookie_name,
        "ip": client_ip,
        "user_agent": data.user_agent or req.headers.get("user-agent", ""),
        "cookies": data.cookies,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    log.append(entry)
    if len(log) > 5000:
        log = log[-5000:]
    save_cookies_log(log)
    return {"status": "ok"}

@app.get("/api/admin/cookies")
def admin_get_cookies(
    credentials: HTTPBasicCredentials = Depends(verify_admin),
    page: int = Query(1, ge=1),
    limit: int = Query(50, ge=1, le=200),
):
    log = load_cookies_log()
    log.reverse()
    total = len(log)
    start = (page - 1) * limit
    end = start + limit
    paginated = log[start:end]
    return {
        "cookies": paginated,
        "total": total,
        "page": page,
        "limit": limit,
        "totalPages": (total + limit - 1) // limit,
    }

@app.delete("/api/admin/cookies")
def admin_clear_cookies(credentials: HTTPBasicCredentials = Depends(verify_admin)):
    save_cookies_log([])
    return {"status": "cleared"}

@app.get("/api/admin/cookies/{cookie_id}/download")
def admin_download_cookie(cookie_id: int, credentials: HTTPBasicCredentials = Depends(verify_admin)):
    log = load_cookies_log()
    entry = next((e for e in log if e.get("id") == cookie_id), None)
    if not entry:
        raise HTTPException(status_code=404, detail="Cookie entry not found")
    name = entry.get("name", f"user_{cookie_id}")
    safe_name = sanitize_filename(name) or f"user_{cookie_id}"
    content = f"Source: {entry.get('ip', 'unknown')}\n"
    content += f"User-Agent: {entry.get('user_agent', 'unknown')}\n"
    content += f"Time: {entry.get('timestamp', 'unknown')}\n"
    content += f"\n--- COOKIES ---\n{entry.get('cookies', '')}\n"
    from fastapi.responses import PlainTextResponse
    encoded = quote(f"{safe_name}_cookies.txt", safe='')
    return PlainTextResponse(
        content,
        headers={"Content-Disposition": f"attachment; filename*=UTF-8''{encoded}"},
    )

# ── Admin Routes ─────────────────────────────────────────────────────────────
@app.get("/api/admin/config")
def admin_get_config(credentials: HTTPBasicCredentials = Depends(verify_admin)):
    return load_ads_config()


@app.post("/api/admin/config")
def admin_update_config(
    update: AdsConfigUpdate,
    credentials: HTTPBasicCredentials = Depends(verify_admin)
):
    config = load_ads_config()
    if update.top_banner is not None:
        config["top_banner"] = update.top_banner
    if update.right_banner is not None:
        config["right_banner"] = update.right_banner
    if update.bottom_banner is not None:
        config["bottom_banner"] = update.bottom_banner
    if update.redirect_ads is not None:
        config["redirect_ads"] = update.redirect_ads
    if update.admin_password is not None and update.admin_password.strip():
        config["admin_password"] = update.admin_password.strip()
    if update.side_banner_left is not None:
        config["side_banner_left"] = update.side_banner_left
    if update.side_banner_right is not None:
        config["side_banner_right"] = update.side_banner_right
    save_ads_config(config)
    return {"status": "saved"}


@app.get("/api/admin/free-status")
def free_download_status(req: Request):
    client_ip = get_client_ip(req)
    log = load_daily_free_log()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    used = log.get(client_ip) == today
    config = load_ads_config()
    enabled = config.get("redirect_ads", {}).get("daily_free_download", False)
    return {"free_available": enabled and not used}


# ── Download Stats API (NEW) ────────────────────────────────────────────────

PLATFORM_COLORS = {
    "YouTube": "#FF0000",
    "Instagram": "#E1306C",
    "TikTok": "#00F2EA",
    "Twitter/X": "#1DA1F2",
    "Facebook": "#1877F2",
    "Other": "#94a3b8",
}

DAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


@app.get("/api/admin/stats")
def admin_get_stats(credentials: HTTPBasicCredentials = Depends(verify_admin)):
    """Return aggregated download statistics for the admin dashboard."""
    log = load_download_log()
    now = datetime.now(timezone.utc)

    # ── Total downloads ──
    total_downloads = len(log)

    # ── Platform breakdown (sorted by count desc) ──
    platform_counts: Dict[str, int] = {}
    for entry in log:
        p = entry.get("platform", "Other")
        platform_counts[p] = platform_counts.get(p, 0) + 1

    total_platform = total_downloads or 1
    platform_stats = [
        {
            "platform": p,
            "count": c,
            "color": PLATFORM_COLORS.get(p, "#94a3b8"),
            "percentage": round((c / total_platform) * 1000) / 10,
        }
        for p, c in sorted(platform_counts.items(), key=lambda x: -x[1])
    ]

    # ── Daily stats (last 7 days) with day names ──
    daily_stats = []
    for i in range(6, -1, -1):
        date_obj = now - timedelta(days=i)
        date_str = date_obj.strftime("%Y-%m-%d")
        day_name = DAY_NAMES[date_obj.weekday()]
        count = 0
        for entry in log:
            ts = entry.get("timestamp", "")
            if ts and ts[:10] == date_str:
                count += 1
        daily_stats.append({"day": day_name, "date": date_str, "downloads": count})

    # ── Today / Week / Month downloads ──
    today_str = now.strftime("%Y-%m-%d")
    week_ago_str = (now - timedelta(days=7)).strftime("%Y-%m-%d")
    month_ago_str = (now - timedelta(days=30)).strftime("%Y-%m-%d")

    today_downloads = 0
    week_downloads = 0
    month_downloads = 0
    for entry in log:
        ts = entry.get("timestamp", "")
        if not ts:
            continue
        entry_date = ts[:10]
        if entry_date == today_str:
            today_downloads += 1
        if entry_date >= week_ago_str:
            week_downloads += 1
        if entry_date >= month_ago_str:
            month_downloads += 1

    # ── Recent downloads (last 20) ──
    sorted_log = sorted(log, key=lambda x: x.get("timestamp", ""), reverse=True)
    recent = []
    for entry in sorted_log[:20]:
        ts = entry.get("timestamp", "")
        time_ago = ""
        if ts:
            try:
                entry_time = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                time_ago = _format_time_ago(entry_time, now)
            except Exception:
                pass
        recent.append({
            "id": entry.get("id", 0),
            "title": entry.get("title", "Unknown"),
            "platform": entry.get("platform", "Other"),
            "quality": entry.get("quality", "—"),
            "size": entry.get("file_size_formatted", "N/A"),
            "time_ago": time_ago,
            "timestamp": ts,
        })

    # ── Total data downloaded ──
    total_size_bytes = sum(e.get("file_size") or 0 for e in log)

    return {
        "totalDownloads": total_downloads,
        "todayDownloads": today_downloads,
        "weeklyDownloads": week_downloads,
        "monthlyDownloads": month_downloads,
        "totalDataBytes": total_size_bytes,
        "totalDataFormatted": format_file_size(total_size_bytes),
        "platformStats": platform_stats,
        "dailyStats": daily_stats,
        "recentDownloads": recent,
    }


@app.get("/api/admin/downloads")
def admin_get_downloads(
    credentials: HTTPBasicCredentials = Depends(verify_admin),
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    platform: Optional[str] = Query(None),
):
    """Return paginated download history for the admin dashboard."""
    log = load_download_log()

    # Filter by platform if specified
    if platform:
        log = [e for e in log if e.get("platform") == platform]

    # Sort by timestamp descending (newest first)
    log.sort(key=lambda x: x.get("timestamp", ""), reverse=True)

    total = len(log)
    start = (page - 1) * limit
    end = start + limit
    paginated = log[start:end]

    # Format relative time for display
    for entry in paginated:
        ts = entry.get("timestamp", "")
        if ts:
            try:
                entry_time = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                entry["time_ago"] = _format_time_ago(entry_time, datetime.now(timezone.utc))
            except Exception:
                entry["time_ago"] = ""
        else:
            entry["time_ago"] = ""

    return {
        "downloads": paginated,
        "total": total,
        "page": page,
        "limit": limit,
        "totalPages": (total + limit - 1) // limit,
    }


def _format_time_ago(past: datetime, now: datetime) -> str:
    """Format a datetime as a human-readable relative time string."""
    diff = now - past
    seconds = int(diff.total_seconds())
    if seconds < 60:
        return "just now"
    elif seconds < 3600:
        return f"{seconds // 60}m ago"
    elif seconds < 86400:
        return f"{seconds // 3600}h ago"
    elif seconds < 604800:
        return f"{seconds // 86400}d ago"
    else:
        return past.strftime("%b %d, %Y")


@app.delete("/api/admin/downloads")
def admin_clear_downloads(credentials: HTTPBasicCredentials = Depends(verify_admin)):
    """Clear all download history."""
@app.get("/api/app-version")
def get_app_version():
    """Returns the latest mobile app version, changelog, and force update requirements."""
    return {
        "latest_version": "3.0.0",
        "version_code": 300,
        "min_version_code": 300,
        "force_update": False,
        "changelog": "• In-App auto updater with zero data loss\n• Snaptube-like transparent share overlay on YouTube/Instagram\n• Direct File Manager & Gallery saving\n• On-device YouTube engine",
        "apk_url": "/download-apk",
        "release_date": "2026-08-31"
    }


@app.get("/download-apk")
def download_latest_apk():
    """Serves the latest release APK file for in-app updates."""
    possible_paths = [
        os.path.join(BASE_DIR, "VidGrab-v3.0.0-release.apk"),
        os.path.join(BASE_DIR, "VidGrab-latest.apk"),
        "/root/vidgrab_backend/VidGrab-v3.0.0-release.apk",
        "/root/vidgrab_backend/VidGrab-latest.apk",
        os.path.join(BASE_DIR, "mobile_app", "build", "app", "outputs", "flutter-apk", "app-release.apk"),
    ]
    for p in possible_paths:
        if os.path.isfile(p):
            return FileResponse(
                p,
                media_type="application/vnd.android.package-archive",
                filename="VidGrab-latest.apk"
            )
    raise HTTPException(status_code=404, detail="APK update binary not found on server")


# Mount Next.js admin static export (built via `npm run build`)
OUT_DIR = os.path.join(BASE_DIR, "out")
if os.path.isdir(OUT_DIR) and os.path.isfile(os.path.join(OUT_DIR, "index.html")):
    app.mount("/_next", StaticFiles(directory=os.path.join(OUT_DIR, "_next")), name="admin_next")
    app.mount("/admin", StaticFiles(directory=OUT_DIR, html=True), name="admin")

# Redirect /admin -> /admin/ (trailing slash required by StaticFiles)
@app.get("/admin", include_in_schema=False)
def admin_root():
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/admin/")

app.mount("/", StaticFiles(directory=FRONTEND_DIR, html=True), name="frontend")